package hakan.rentacar.entities.dtos;

import hakan.rentacar.entities.concretes.Contract;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Schema(description = "Sözleşme bilgileri")
public class ContractDto {

    private Long id;

    @NotNull
    private Long rentalId;

    @NotNull
    private Long customerId;

    private Long templateId;

    private String contractNumber; // Auto-generated by backend

    private LocalDate signedDate; // Auto-generated by backend

    private LocalDateTime signedAt;

    private Contract.ContractStatus status; // Auto-set by backend

    private String terms;

    private String conditions;

    private String customerSignature;

    private String companySignature;

    private String signedBy;

    private LocalDateTime eSignatureVerifiedAt;

    private String eSignatureHash;

    private String pdfPath;

    private String witnessName;

    private LocalDate expiryDate;

    private String notes;

    // Additional fields for response
    private String customerName;
    private String rentalInfo;
    private String templateName;
}

